spring:
  application:
    name: rest
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.86.133:8848
  shardingsphere:
    datasource:
      names: master0,master1,master0slave0,master0slave1,master1slave0,master1slave1
      master0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_0
        username: root
        password: 123456
      master0slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_0_slave_0
        username: root
        password: 123456
      master0slave1:
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/demo_ds_master_0_slave_1
          username: root
          password: 123456

      master1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_1
        username: root
        password: 123456
      master1slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_1_slave_0
        username: root
        password: 123456
      master1slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_master_1_slave_1
        username: root
        password: 123456

    sharding:
      tables:
        t_order:
          actual-data-nodes: ds$->{0..1}.t_order
      binding-tables: t_order
      default-database-strategy:
        complex:
          sharding-columns: order_id
          algorithm-class-name: com.kevin.sharding.OrderSharding
      master-slave-rules:
        ds0:
          master-data-source-name: master0
          slave-data-source-names: master0slave0, master0slave1
        ds1:
          master-data-source-name: master1
          slave-data-source-names: master1slave0, master1slave1
    props:
      sql:
        show: true
management:
  endpoint:
    web:
      exposure:
        include: /*

logging.level.root: ERROR
logging.level.com.kevin: DEBUG
