spring:
  application:
    name: user

sharding:
  jdbc:
    datasource:
      names: master,slave
      master:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_0
        username: root
        password: 123456
      slave:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo_ds_1
        username: root
        password: 123456
    config:
      masterslave:
        name: ms
        master-data-source-name: master
        slave-data-source-names: slave
      props:
        sql:
          show: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging.level.root: ERROR
logging.level.com.kevin: DEBUG
