server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: http://127.0.0.1:8082
        predicates:
        - Host=127.0.0.1:8083

  logging.level.root: ERROR
  logging.level.com.kevin: DEBUG